### ISSUE TITLE
Auto Save

### ISSUE THREAD

**Issue by Lugoues** [spacejam/void#9]
Auto saving would catch this up to modern editors.

**Comment by spacejam** [comment]
Saving is automatic. Saving occurs during a program-initiated exit. Saving does not occur automatically after every edit, because this program is still under heavy development, and occasionally while creating features I will create bugs, and I prefer NOT to serialize the buggy behavior. I may add a signal handler to trigger saves when signals are received, though.

**Comment by igalic** [comment]
so i was just wondering where my data goes after a reboot
This answers my question!
Handling a `SIGTERM` would be really good…
